//
//  ProductListingPresenter.swift
//  Dishwashers
//
//  Created by Darren Allen on 19/06/2018.
//  Copyright (c) 2018 Swift7Media. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

protocol ProductListingPresenterInput
{
    func presentRetrievalError()
    func presentProducts(products: [Product], count: Int)
}

class ProductListingPresenter: ProductListingPresenterInput
{
    weak var output: ProductListingViewControllerInput?

    // MARK: - Presentation logic
    func presentRetrievalError()
    {
        output?.displayError(withTitle: "Sorry", andMessage: "There seems to have been a problem getting a list of products, please try again later.")
    }
    
    func presentProducts(products: [Product], count: Int)
    {
        output?.displayProductList(withProducts: products, count: count)
    }
}
