//
//  ProductDetailsBuilder.swift
//  Dishwashers
//
//  Created by Darren Allen on 19/06/2018.
//  Copyright (c) 2018 Swift7Media. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Build module, inject dependencies and return view controller
class ProductDetailsBuilder
{
    // MARK: - Configuration
    static func viewController(withProductID productID: String) -> ProductDetailsViewController
    {
        let viewController = ProductDetailsViewController()
        let router = ProductDetailsRouter()
        let presenter = ProductDetailsPresenter()
        let interactor = ProductDetailsInteractor(productID: productID)

        router.viewController = viewController
        presenter.output = viewController
        interactor.output = presenter
        viewController.output = interactor
        viewController.router = router

        return viewController
    }
}
