//
//  ProductDetailsInteractor.swift
//  Dishwashers
//
//  Created by Darren Allen on 19/06/2018.
//  Copyright (c) 2018 Swift7Media. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation

protocol ProductDetailsInteractorInput
{
    func getProductDetails()
}

class ProductDetailsInteractor: ProductDetailsInteractorInput
{
    var output: ProductDetailsPresenterInput?
    var worker: ProductDetailsWorkerTasks
    var productID: String
    var apiManager = APIManager.sharedInstance

    required init(worker: ProductDetailsWorkerTasks = ProductDetailsWorker(), productID: String)
    {
        self.worker = worker
        self.productID = productID
    }

    // MARK: - Business logic
    
    func getProductDetails()
    {
        apiManager.retrieveProductDetail(withProductID: self.productID) { (productdetails, error) in
            if let details = productdetails
            {
                self.output?.presentProductDetails(withDetails: details)
            }
        }
    }
}
